# İş akışının adı (GitHub Actions sekmesinde görünecek)
name: Otomatik Liste Guncelleyici

on:
  # Bu satır, "Actions" sekmesinden elle çalıştırma düğmesi ekler (ilk test için gerekli)
  workflow_dispatch:

  # Bu bölüm, zamanlanmış görevi ayarlar
  schedule:
    # "cron" formatı: Dakika Saat Gün Ay HaftaGünü
    # Aşağıdaki '0 2 * * *' ifadesi "Her gece UTC saatiyle 02:00'de çalıştır" demektir.
    - cron: '0 2 * * *'

jobs:
  build:
    # Görevin çalışacağı sanal makine türü
    runs-on: ubuntu-latest

    # Görevin adımları
    steps:
      # 1. Adım: Proje dosyalarını sanal makineye indirir
      - name: Proje Dosyalarını Indir
        uses: actions/checkout@v4

      # 2. Adım: .NET 8 SDK'yı kurar
      - name: .NET 8 Kurulumu
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # 3. Adım: HostlistCompiler'ı çalıştırarak listeyi oluşturur
      - name: Listeyi Olustur
        run: dotnet run --project src/HostlistCompiler -c src/HostlistCompiler/config.json

      # 4. Adım: Oluşturulan yeni listeyi otomatik olarak projeye kaydeder
      - name: Degisiklikleri Projeye Kaydet
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Filtre listesi otomatik olarak güncellendi"
